### ISSUE TITLE
colorization not auto-applied

### ISSUE THREAD

**Issue by honglooker** [fowles/pratdiff#1]
Based on what I saw @ https://github.com/fowles/pratdiff/blob/main/src/main.rs#L30 
I thought that colorization would be on by default. 

I made this my main diff tool in jj:
`diff.tool = "pratdiff"` // after `jj config edit --user`
when I did `jj diff`, I didn't see any colors.

In order to get the colors, I had to update the config:
`diff.tool = ["pratdiff", "--color=always", "$left", "$right"]`

Maybe a `jj` thing and WAI? In any case, thanks :)

**Comment by fowles** [comment]
The detection works by whether or not it is going to stdout (not all pagers handle colors properly).  `jj` sends things to a pager that is correctly configured for color, but pratdiff can't tell
